export { default as Blockquote } from './Blockquote/Blockquote'
export { default as Button } from './Button/Button'
export { default as Footer } from './Footer/Footer'
export { default as Header } from './Header/Header'
export { default as Page } from './Page/Page'
